#!/usr/bin/env python3
"""
generate_spec.py
================
PyInstaller の build.spec を動的に生成するスクリプト。
GitHub Actions の build.yml から呼び出される。

PaddleOCR v3 は PaddleX に依存しており、設定YAMLが同梱されないと
"The pipeline (OCR) does not exist!" エラーになる。
このスクリプトはその設定ファイルを明示的に収集して spec に含める。
"""

import os
import pathlib
import sys

# ── パス収集 ─────────────────────────────────────────────────────────────────

import paddlex
import paddleocr

paddlex_dir  = pathlib.Path(paddlex.__file__).parent
paddleocr_dir = pathlib.Path(paddleocr.__file__).parent
paddle_cache  = pathlib.Path.home() / ".paddleocr"
poppler_bin   = os.environ.get("POPPLER_BIN", "")

print(f"[generate_spec] paddlex_dir  : {paddlex_dir}")
print(f"[generate_spec] paddleocr_dir: {paddleocr_dir}")
print(f"[generate_spec] paddle_cache : {paddle_cache}")
print(f"[generate_spec] poppler_bin  : {poppler_bin}")

# ── Poppler バイナリ ──────────────────────────────────────────────────────────

poppler_entries = []
for exe in ["pdftoppm.exe", "pdfinfo.exe", "pdftopdf.exe", "pdftotext.exe"]:
    p = pathlib.Path(poppler_bin) / exe
    if p.exists():
        poppler_entries.append(f"    (r'{p}', 'poppler'),")

poppler_block = "\n".join(poppler_entries)

# ── PaddleX YAML ─────────────────────────────────────────────────────────────
# 設定YAMLがないと "pipeline does not exist" エラーになる

yaml_entries = []
for ext in ("*.yaml", "*.yml"):
    for yaml_file in sorted(paddlex_dir.rglob(ext)):
        rel_dir = str(yaml_file.relative_to(paddlex_dir.parent).parent).replace("\\", "/")
        yaml_entries.append(f"    (r'{yaml_file}', r'{rel_dir}'),")

yaml_block = "\n".join(yaml_entries)

# ── モデルキャッシュ ──────────────────────────────────────────────────────────

cache_block = ""
if paddle_cache.exists():
    cache_block = f"    (r'{paddle_cache}', '.paddleocr'),"

# ── spec 生成 ─────────────────────────────────────────────────────────────────

spec_content = f"""\
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by generate_spec.py

import pathlib
from PyInstaller.utils.hooks import collect_all, collect_data_files

# --- Poppler ---
binaries_poppler = [
{poppler_block}
]

# --- tkinterdnd2 ---
datas_tk, binaries_tk, hiddenimports_tk = collect_all('tkinterdnd2')

# --- paddleocr ---
datas_paddle, binaries_paddle, hiddenimports_paddle = collect_all('paddleocr')

# --- paddlex ---
datas_paddlex, binaries_paddlex, hiddenimports_paddlex = collect_all('paddlex')

# --- PaddleX YAML configs (explicit) ---
extra_datas = [
{yaml_block}
{cache_block}
]

a = Analysis(
    ['bridge_pdf_link_app.py'],
    binaries=(
        binaries_poppler
        + binaries_tk
        + binaries_paddle
        + binaries_paddlex
    ),
    datas=(
        datas_tk
        + datas_paddle
        + datas_paddlex
        + extra_datas
    ),
    hiddenimports=(
        hiddenimports_tk
        + hiddenimports_paddle
        + hiddenimports_paddlex
        + [
            'PIL._tkinter_finder',
            'paddle',
            'paddleocr',
            'paddlex',
            'paddlex.inference',
            'paddlex.inference.pipelines',
            'paddlex.inference.pipelines.ocr',
        ]
    ),
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    name='橋梁点検PDFリンク追加ツール',
    console=False,
    onefile=True,
)
"""

out_path = pathlib.Path("build.spec")
out_path.write_text(spec_content, encoding="utf-8")
print(f"[generate_spec] build.spec を生成しました ({out_path.stat().st_size} bytes)")
